/**
 * File Name : app/(public)/github/complete/route.ts
 * Description : 깃허브 소셜 로그인 기능
 * Author : 임도헌
 *
 * History
 * Date        Author   Status    Description
 * 2024.10.08  임도헌   Created
 * 2024.10.08  임도헌   Modified  깃허브 소셜 로그인 기능 추가
 * 2025.06.05  임도헌   Modified  Token, Profile 관련 함수 모듈화
 * 2025.12.09  임도헌   Modified  OAuth state 검증 및 세션에 유저 ID 저장 로직 직접 처리
 * 2025.12.12  임도헌   Modified  state를 쿠키 기반으로 검증하고, 완료 후 쿠키 제거
 * 2025.12.12  임도헌   Modified  NextResponse.redirect에 절대 URL 사용하도록 수정
 * 2026.01.20  임도헌   Modified  Service 로직 분리, 에러 핸들링 강화, 리다이렉트 헬퍼 적용
 * 2026.02.11  임도헌   Modified  정지 유저 체크 로직 강화 및 에러 리다이렉트
 * 2026.03.08  임도헌   Modified  callbackUrl 복원 및 정지 유저 로그인 복귀 경로 보존
 * 2026.03.12  임도헌   Modified  토큰 교환, 프로필 조회, 정지 유저 분기, callbackUrl 복귀 흐름 명확화
 * 2026.03.14  임도헌   Modified  로그인 직후 최소 프로필/지역 누락 계정은 onboarding으로 보내도록 최종 복귀 경로 공통화
 * 2026.03.25  임도헌   Modified  GitHub 자동 생성 닉네임 계정은 첫 로그인 시 닉네임 온보딩도 함께 노출
 * 2026.04.12  임도헌   Moved     파일 경로를 app/(auth)/github/complete/route.ts 에서 app/(public)/github/complete/route.ts 로 변경 (라우트 그룹 개편)
 * 2026.08.30  임도헌   Modified  OAuth 실패 복귀 시 기본 프로필 callbackUrl 쿼리 생략
 */

import { NextRequest, NextResponse } from "next/server";
import {
  findOrCreateGitHubUser,
  getGitHubAccessToken,
  getGitHubUserProfile,
  isGitHubAutoGeneratedUsername,
} from "@/features/auth/service/github";
import { saveUserSession } from "@/features/auth/service/authSession";
import { resolvePostAuthRedirectPath } from "@/features/auth/service/onboarding";
import {
  buildAuthFlowHref,
  sanitizeCallbackUrl,
} from "@/features/auth/utils/redirect";
import db from "@/lib/db";

/**
 * GitHub OAuth 완료 라우트
 *
 * 처리 흐름
 * - code/state 파라미터와 저장된 쿠키 검증
 * - 액세스 토큰 발급 및 GitHub 프로필 조회
 * - 유저 조회/생성 후 정지 상태 확인
 * - 유효한 계정이면 세션 생성 후 callbackUrl로 복귀
 *
 * @param {NextRequest} request - OAuth 콜백 요청 객체
 */
export async function GET(request: NextRequest) {
  const code = request.nextUrl.searchParams.get("code");
  const state = request.nextUrl.searchParams.get("state");
  const storedState = request.cookies.get("gh_oauth_state")?.value;
  const callbackUrl = sanitizeCallbackUrl(
    request.cookies.get("gh_oauth_callback_url")?.value ?? "/profile"
  );

  // 에러 발생 시 로그인 화면으로 복귀시키는 공통 헬퍼
  const returnToLogin = (errorType: string) => {
    const url = new URL(buildAuthFlowHref("/login", callbackUrl), request.url);
    url.searchParams.set("error", errorType);
    const res = NextResponse.redirect(url);
    res.cookies.delete("gh_oauth_state"); // 쿠키 정리
    res.cookies.delete("gh_oauth_callback_url");
    return res;
  };

  // 필수 파라미터 검증
  if (!code) return returnToLogin("github_code_missing");

  // CSRF 방지용 state 검증
  if (!state || !storedState || state !== storedState) {
    return returnToLogin("github_state_mismatch");
  }

  try {
    // 토큰 발급 -> 프로필 조회 -> 유저 처리
    const accessToken = await getGitHubAccessToken(code);
    const profile = await getGitHubUserProfile(accessToken);
    const userId = await findOrCreateGitHubUser(profile);

    // 정지 상태 확인 및 기간 만료 시 자동 해제
    const user = await db.user.findUnique({
      where: { id: userId },
      select: { username: true, bannedAt: true, bannedUntil: true },
    });

    if (user?.bannedAt) {
      const now = new Date();
      if (user.bannedUntil && now > user.bannedUntil) {
        // 기간 만료 자동 해제
        await db.user.update({
          where: { id: userId },
          data: { bannedAt: null, bannedUntil: null },
        });
      } else {
        // 정지 유지 시 로그인 차단
        return returnToLogin("banned_user");
      }
    }

    // 로그인 세션 저장
    await saveUserSession(userId);

    // 성공 시 callbackUrl로 복귀
    const forceUsernameSetup = !!user?.username
      ? isGitHubAutoGeneratedUsername(user.username, profile.login)
      : false;
    const redirectTo = await resolvePostAuthRedirectPath(userId, callbackUrl, {
      forceUsernameSetup,
    });
    const response = NextResponse.redirect(new URL(redirectTo, request.url));
    response.cookies.delete("gh_oauth_state");
    response.cookies.delete("gh_oauth_callback_url");
    return response;
  } catch (error) {
    console.error("GitHub Login Error:", error);
    return returnToLogin("github_login_failed");
  }
}
