/**
 * File Name : app/(public)/kakao/complete/route.ts
 * Description : 카카오 소셜 로그인 완료 처리 및 세션 생성
 * Author : 임도헌
 *
 * History
 * Date        Author   Status    Description
 * 2026.02.24  임도헌   Created   카카오 콜백 처리, state 검증, Lazy Unban 및 세션 생성
 * 2026.03.08  임도헌   Modified  callbackUrl 복원 및 정지 유저 로그인 복귀 경로 보존
 * 2026.03.12  임도헌   Modified  토큰 교환, 프로필 조회, 정지 유저 분기, callbackUrl 복귀 흐름 명확화
 * 2026.03.14  임도헌   Modified  로그인 직후 최소 프로필/지역 누락 계정은 onboarding으로 보내도록 최종 복귀 경로 공통화
 * 2026.03.25  임도헌   Modified  카카오 자동 생성 닉네임 계정은 첫 로그인 시 닉네임 온보딩도 함께 노출
 * 2026.04.12  임도헌   Moved     파일 경로를 app/(auth)/kakao/complete/route.ts 에서 app/(public)/kakao/complete/route.ts 로 변경 (라우트 그룹 개편)
*/

import { NextRequest, NextResponse } from "next/server";
import {
  findOrCreateKakaoUser,
  getKakaoAccessToken,
  getKakaoUserProfile,
  isKakaoAutoGeneratedUsername,
} from "@/features/auth/service/kakao";
import { saveUserSession } from "@/features/auth/service/authSession";
import { resolvePostAuthRedirectPath } from "@/features/auth/service/onboarding";
import { sanitizeCallbackUrl } from "@/features/auth/utils/redirect";
import db from "@/lib/db";

/**
 * 카카오 OAuth 완료 라우트
 *
 * 처리 흐름
 * - code/state 파라미터와 저장된 쿠키 검증
 * - 액세스 토큰 발급 및 카카오 프로필 조회
 * - 유저 조회/생성 후 정지 상태 확인
 * - 유효한 계정이면 세션 생성 후 callbackUrl로 복귀
 *
 * @param {NextRequest} request - OAuth 콜백 요청 객체
 */
export async function GET(request: NextRequest) {
  const code = request.nextUrl.searchParams.get("code");
  const state = request.nextUrl.searchParams.get("state");
  const storedState = request.cookies.get("kakao_oauth_state")?.value;
  const callbackUrl = sanitizeCallbackUrl(
    request.cookies.get("kakao_oauth_callback_url")?.value ?? "/profile"
  );

  // 에러 발생 시 로그인 화면으로 복귀시키는 공통 헬퍼
  const returnToLogin = (errorType: string) => {
    const url = new URL("/login", request.url);
    url.searchParams.set("error", errorType);
    url.searchParams.set("callbackUrl", callbackUrl);
    const res = NextResponse.redirect(url);
    res.cookies.delete("kakao_oauth_state"); // 쿠키 정리
    res.cookies.delete("kakao_oauth_callback_url");
    return res;
  };

  // 필수 파라미터 검증
  if (!code) return returnToLogin("kakao_code_missing");

  // CSRF 방지용 state 검증
  if (!state || !storedState || state !== storedState) {
    return returnToLogin("kakao_state_mismatch");
  }

  try {
    // 토큰 발급 -> 프로필 조회 -> 유저 처리
    const accessToken = await getKakaoAccessToken(code);
    const profile = await getKakaoUserProfile(accessToken);
    const userId = await findOrCreateKakaoUser(profile);

    // 정지 상태 확인 및 기간 만료 시 자동 해제
    const user = await db.user.findUnique({
      where: { id: userId },
      select: { username: true, bannedAt: true, bannedUntil: true },
    });

    if (user?.bannedAt) {
      const now = new Date();
      if (user.bannedUntil && now > user.bannedUntil) {
        // 기간 만료 자동 해제
        await db.user.update({
          where: { id: userId },
          data: { bannedAt: null, bannedUntil: null },
        });
      } else {
        // 정지 유지 시 로그인 차단
        return returnToLogin("banned_user");
      }
    }

    // 로그인 세션 저장
    await saveUserSession(userId);

    // 성공 시 callbackUrl로 복귀
    const forceUsernameSetup = !!user?.username
      ? isKakaoAutoGeneratedUsername(
          user.username,
          profile.kakao_account?.profile?.nickname || "kakao"
        )
      : false;
    const redirectTo = await resolvePostAuthRedirectPath(userId, callbackUrl, {
      forceUsernameSetup,
    });
    const response = NextResponse.redirect(new URL(redirectTo, request.url));
    response.cookies.delete("kakao_oauth_state");
    response.cookies.delete("kakao_oauth_callback_url");
    return response;
  } catch (error) {
    console.error("Kakao Login Error:", error);
    return returnToLogin("kakao_login_failed");
  }
}

