/**
 * File Name : features/auth/service/github.ts
 * Description : GitHub OAuth 인증 및 유저 처리 비즈니스 로직
 * Author : 임도헌
 *
 * History
 * Date        Author   Status    Description
 * 2025.05.30  임도헌   Created
 * 2025.05.30  임도헌   Modified  getAccessToken, getGithubProfile 함수로 분리
 * 2026.01.19  임도헌   Moved     lib/auth -> features/auth/lib
 * 2026.01.20  임도헌   Renamed   oauth.ts -> service.ts
 * 2026.01.20  임도헌   Modified  GitHub OAuth 로직 통합 (Token/Profile/User DB)
 * 2026.01.21  임도헌   Moved     lib/github/service -> service/github
 * 2026.01.25  임도헌   Modified  주석 보강
 * 2026.02.23  임도헌   Modified  신규 생성 시 닉네임 중복 충돌(P2002) 방어를 위해 재시도 로직 추가
 * 2026.03.25  임도헌   Modified  GitHub 자동 생성 닉네임 여부를 콜백에서 판별할 수 있도록 헬퍼 추가
 * 2026.04.02  임도헌   Modified  GitHub 닉네임 helper JSDoc 보강
 * 2026.04.04  임도헌   Modified  OAuth 유저 매칭/닉네임 충돌 방어 단계의 인라인 주석 보강
 * 2026.06.04  임도헌   Modified  GitHub 자동 생성 유저명 길이와 충돌 회피 기준을 공용 상수로 통일
 */

import "server-only";
import crypto from "node:crypto";
import { AUTH_ERRORS } from "@/features/auth/constants";
import db from "@/lib/db";
import { USERNAME_MAX_LENGTH } from "@/lib/constants";
import { isUniqueConstraintError } from "@/lib/errors";
import type { GitHubProfile } from "@/features/auth/types";

const GITHUB_AUTO_USERNAME_SUFFIX_REGEX = /^[0-9a-f]{4}$/i;

/**
 * GitHub 로그인 기반 기본 유저명 생성
 *
 * @param {string} login - GitHub 로그인 ID
 * @returns {string} `-gh` 접미사가 포함된 기본 유저명
 */
function buildGitHubBaseUsername(login: string) {
  const baseUsername = `${login}-gh`.toLowerCase();
  return baseUsername.length > USERNAME_MAX_LENGTH
    ? baseUsername.slice(0, USERNAME_MAX_LENGTH)
    : baseUsername;
}

function buildGitHubFallbackUsername(baseUsername: string, randomSuffix: string) {
  const prefixLength = USERNAME_MAX_LENGTH - randomSuffix.length - 1;
  return `${baseUsername.slice(0, prefixLength)}_${randomSuffix}`;
}

function getGitHubCollisionPrefixes(baseUsername: string) {
  const currentPrefixLength = USERNAME_MAX_LENGTH - 4 - 1;
  return Array.from(
    new Set([baseUsername.slice(0, currentPrefixLength), baseUsername.slice(0, 5)])
  ).map((prefix) => `${prefix}_`);
}

/**
 * 현재 유저명이 GitHub 자동 생성 규칙과 일치하는지 판별
 *
 * @param {string} username - 현재 저장된 유저명
 * @param {string} login - GitHub 로그인 ID
 * @returns {boolean} 자동 생성 닉네임이면 true
 */
export function isGitHubAutoGeneratedUsername(
  username: string,
  login: string
) {
  const normalizedUsername = username.trim().toLowerCase();
  const baseUsername = buildGitHubBaseUsername(login);

  // 기본 생성 규칙과 완전히 일치하는 경우
  if (normalizedUsername === baseUsername) {
    return true;
  }

  // 충돌 회피용 suffix가 붙은 자동 생성 닉네임 판별
  return getGitHubCollisionPrefixes(baseUsername).some((collisionPrefix) => {
    const randomSuffix = normalizedUsername.slice(collisionPrefix.length);

    return (
      normalizedUsername.startsWith(collisionPrefix) &&
      randomSuffix.length === 4 &&
      GITHUB_AUTO_USERNAME_SUFFIX_REGEX.test(randomSuffix)
    );
  });
}

/**
 * GitHub 인증 코드(code)로 액세스 토큰을 요청
 *
 * @param {string} code - GitHub Redirect URL에서 받은 code
 * @returns {Promise<string>} Access Token 문자열
 * @throws {Error} 토큰 발급 실패 시 에러 발생
 */
export async function getGitHubAccessToken(code: string): Promise<string> {
  const params = new URLSearchParams({
    client_id: process.env.GITHUB_CLIENT_ID!,
    client_secret: process.env.GITHUB_CLIENT_SECRET!,
    code,
  }).toString();

  const url = `https://github.com/login/oauth/access_token?${params}`;

  const response = await fetch(url, {
    method: "POST",
    headers: { Accept: "application/json" },
  });

  const { error, access_token } = await response.json();

  if (error || !access_token) {
    throw new Error(AUTH_ERRORS.GITHUB_TOKEN_FAILED);
  }

  return access_token;
}

/**
 * 액세스 토큰으로 GitHub 유저 프로필 정보를 조회
 *
 * @param {string} accessToken - GitHub Access Token
 * @returns {Promise<GitHubProfile>} 깃허브 프로필 객체
 * @throws {Error} 프로필 조회 실패 시 에러 발생
 */
export async function getGitHubUserProfile(
  accessToken: string
): Promise<GitHubProfile> {
  const response = await fetch("https://api.github.com/user", {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
    cache: "no-cache",
  });

  if (!response.ok) {
    throw new Error(AUTH_ERRORS.GITHUB_PROFILE_FAILED);
  }

  return await response.json();
}

/**
 * GitHub 프로필 정보로 유저를 찾거나 새로 생성
 * - 닉네임 충돌 시 난수를 부여하여 가입이 블락되지 않도록 방어
 *
 * @param {GitHubProfile} profile - GitHub 프로필 정보
 * @returns {Promise<number>} 유저 ID
 */
export async function findOrCreateGitHubUser(
  profile: GitHubProfile
): Promise<number> {
  const githubIdStr = String(profile.id);

  // github_id 기준의 기존 계정 매칭
  const existingUser = await db.user.findUnique({
    where: { github_id: githubIdStr },
    select: { id: true },
  });

  if (existingUser) return existingUser.id;

  // GitHub login 기반 기본 유저명 구성
  const baseUsername = buildGitHubBaseUsername(profile.login);

  try {
    // 기본 유저명으로 1차 생성 시도
    const newUser = await db.user.create({
      data: {
        username: baseUsername,
        github_id: githubIdStr,
        avatar: profile.avatar_url,
      },
      select: { id: true },
    });
    return newUser.id;
  } catch (error) {
    // 닉네임 중복 시 짧은 난수 suffix 기반 2차 생성
    if (isUniqueConstraintError(error, ["username"])) {
      const randomSuffix = crypto.randomBytes(2).toString("hex"); // 4글자 난수
      const safeUsername = buildGitHubFallbackUsername(
        baseUsername,
        randomSuffix
      );

      const fallbackUser = await db.user.create({
        data: {
          username: safeUsername,
          github_id: githubIdStr,
          avatar: profile.avatar_url,
        },
        select: { id: true },
      });
      return fallbackUser.id;
    }

    throw error;
  }
}
