/**
 * File Name : features/auth/service/kakao.ts
 * Description : Kakao OAuth 인증 및 유저 처리 비즈니스 로직
 * Author : 임도헌
 *
 * History
 * Date        Author   Status    Description
 * 2026.02.24  임도헌   Created   카카오 로그인 토큰 발급, 프로필 조회, 유저 생성 로직 구현
 * 2026.03.25  임도헌   Modified  카카오 자동 생성 닉네임 여부를 콜백에서 판별할 수 있도록 헬퍼 추가
 * 2026.04.02  임도헌   Modified  카카오 닉네임 helper JSDoc 보강
 * 2026.04.04  임도헌   Modified  OAuth 유저 생성 재시도 단계의 인라인 주석 보강
 * 2026.06.04  임도헌   Modified  Kakao 자동 생성 유저명 길이와 충돌 회피 기준을 공용 상수로 통일
 */

import "server-only";
import crypto from "node:crypto";
import { AUTH_ERRORS } from "@/features/auth/constants";
import db from "@/lib/db";
import { USERNAME_MAX_LENGTH } from "@/lib/constants";
import { isUniqueConstraintError } from "@/lib/errors";
import type { KakaoProfile } from "@/features/auth/types";

const KAKAO_AUTO_USERNAME_SUFFIX_REGEX = /^[0-9a-f]{4}$/i;
const KAKAO_FINAL_AUTO_USERNAME_REGEX = /^kk_[0-9a-f]{6}$/i;

/**
 * 카카오 로그인 기반 기본 유저명 생성
 *
 * @param {string} nickname - 카카오 프로필 닉네임
 * @returns {string} `-kk` 접미사가 포함된 기본 유저명
 */
function buildKakaoBaseUsername(nickname: string) {
  const baseUsername = `${nickname}-kk`.toLowerCase();
  return baseUsername.length > USERNAME_MAX_LENGTH
    ? baseUsername.slice(0, USERNAME_MAX_LENGTH)
    : baseUsername;
}

function buildKakaoFallbackUsername(baseUsername: string, randomSuffix: string) {
  const prefixLength = USERNAME_MAX_LENGTH - randomSuffix.length - 1;
  return `${baseUsername.slice(0, prefixLength)}_${randomSuffix}`;
}

function getKakaoCollisionPrefixes(baseUsername: string) {
  const currentPrefixLength = USERNAME_MAX_LENGTH - 4 - 1;
  return Array.from(
    new Set([baseUsername.slice(0, currentPrefixLength), baseUsername.slice(0, 5)])
  ).map((prefix) => `${prefix}_`);
}

/**
 * 현재 유저명이 카카오 자동 생성 규칙과 일치하는지 판별
 *
 * @param {string} username - 현재 저장된 유저명
 * @param {string} nickname - 카카오 프로필 닉네임
 * @returns {boolean} 자동 생성 닉네임이면 true
 */
export function isKakaoAutoGeneratedUsername(
  username: string,
  nickname: string
) {
  const normalizedUsername = username.trim().toLowerCase();
  const baseUsername = buildKakaoBaseUsername(nickname);

  // 기본 생성 규칙 또는 최종 fallback 규칙 일치 여부
  if (
    normalizedUsername === baseUsername ||
    KAKAO_FINAL_AUTO_USERNAME_REGEX.test(normalizedUsername)
  ) {
    return true;
  }

  // 충돌 회피용 suffix가 붙은 자동 생성 닉네임 판별
  return getKakaoCollisionPrefixes(baseUsername).some((collisionPrefix) => {
    const randomSuffix = normalizedUsername.slice(collisionPrefix.length);

    return (
      normalizedUsername.startsWith(collisionPrefix) &&
      randomSuffix.length === 4 &&
      KAKAO_AUTO_USERNAME_SUFFIX_REGEX.test(randomSuffix)
    );
  });
}

/**
 * 카카오 인증 코드(code)로 액세스 토큰을 요청
 *
 * - 카카오 REST API는 `x-www-form-urlencoded` 형식을 요구함
 * - POST 요청을 통해 Access Token을 발급받음
 *
 * @param code - 카카오 Redirect URI에서 전달받은 인가 코드
 * @returns Access Token 문자열
 * @throws {Error} 토큰 발급 실패 시 에러 발생
 */
export async function getKakaoAccessToken(code: string): Promise<string> {
  const params = new URLSearchParams({
    grant_type: "authorization_code",
    client_id: process.env.KAKAO_CLIENT_ID!,
    client_secret: process.env.KAKAO_CLIENT_SECRET!,
    redirect_uri: process.env.KAKAO_REDIRECT_URI!,
    code,
  }).toString();

  const url = "https://kauth.kakao.com/oauth/token";

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded;charset=utf-8",
    },
    body: params,
    cache: "no-store",
  });

  const data = await response.json();

  if (data.error || !data.access_token) {
    console.error("Kakao Token Error:", data);
    throw new Error(AUTH_ERRORS.KAKAO_TOKEN_FAILED);
  }

  return data.access_token;
}

/**
 * 액세스 토큰으로 카카오 유저 프로필 정보를 조회
 *
 * @param accessToken - 카카오 Access Token
 * @returns 카카오 프로필 객체 (KakaoProfile)
 * @throws {Error} 프로필 조회 실패 시 에러 발생
 */
export async function getKakaoUserProfile(
  accessToken: string
): Promise<KakaoProfile> {
  const response = await fetch("https://kapi.kakao.com/v2/user/me", {
    method: "GET",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-type": "application/x-www-form-urlencoded;charset=utf-8",
    },
    cache: "no-store",
  });

  if (!response.ok) {
    throw new Error(AUTH_ERRORS.KAKAO_PROFILE_FAILED);
  }

  return await response.json();
}

/**
 * 카카오 프로필 정보로 유저를 찾거나 새로 생성
 *
 * [로직]
 * 1. `kakao_id`로 기존 유저가 있는지 확인하고 있으면 ID 반환
 * 2. 신규 유저일 경우 닉네임, 이메일, 아바타 정보를 파싱 (선택 동의 대비 Optional 처리)
 * 3. `username` 뒤에 `-kk` 접미사를 붙여 생성 시도
 * 4. P2002(Unique 중복) 에러 발생 시 방어 로직 실행:
 *    - 이메일 중복 시: 이메일을 제외하고 가입 시도
 *    - 닉네임 중복 시: 닉네임 뒤에 난수를 붙여 재시도
 *
 * @param profile - 카카오 프로필 정보
 * @returns 유저 ID
 */
export async function findOrCreateKakaoUser(
  profile: KakaoProfile
): Promise<number> {
  const kakaoIdStr = String(profile.id);

  // kakao_id 기준의 기존 계정 매칭
  const existingUser = await db.user.findUnique({
    where: { kakao_id: kakaoIdStr },
    select: { id: true },
  });

  if (existingUser) return existingUser.id;

  // 선택 동의 항목을 포함한 신규 유저 데이터 파싱
  const account = profile.kakao_account;
  const nickname = account?.profile?.nickname || "kakao";

  // 기본 프로필 이미지 또는 미동의 항목의 null 정규화
  const avatar = account?.profile?.is_default_image
    ? null
    : account?.profile?.profile_image_url || null;

  // 이메일 미동의 계정의 null 처리
  const email = account?.email || null;

  // 카카오 닉네임 기반 기본 유저명 구성
  const baseUsername = buildKakaoBaseUsername(nickname);

  // 재시도 단계에서 재사용할 공통 생성 헬퍼
  const attemptCreateUser = async (
    usernameData: string,
    emailData: string | null
  ) => {
    return await db.user.create({
      data: {
        username: usernameData,
        kakao_id: kakaoIdStr,
        avatar,
        email: emailData,
      },
      select: { id: true },
    });
  };

  try {
    // 기본 정보 기준의 1차 생성 시도
    const newUser = await attemptCreateUser(baseUsername, email);
    return newUser.id;
  } catch (error) {
    // P2002 기준의 이메일/닉네임 충돌 방어
    if (isUniqueConstraintError(error)) {
      const isEmailTaken = isUniqueConstraintError(error, ["email"]);
      const isUsernameTaken = isUniqueConstraintError(error, ["username"]);

      // 충돌 필드만 제거/치환한 안전 payload 구성
      const safeEmail = isEmailTaken ? null : email;
      const randomSuffix = crypto.randomBytes(2).toString("hex");
      const safeUsername = isUsernameTaken
        ? buildKakaoFallbackUsername(baseUsername, randomSuffix)
        : baseUsername;

      try {
        // 보정 payload 기준의 2차 생성 시도
        const fallbackUser = await attemptCreateUser(safeUsername, safeEmail);
        return fallbackUser.id;
      } catch (fallbackError) {
        // 난수 suffix까지 겹쳤을 때의 최종 fallback
        if (isUniqueConstraintError(fallbackError, ["username"])) {
          const finalUsername = `kk_${crypto.randomBytes(3).toString("hex")}`;
          const finalUser = await attemptCreateUser(finalUsername, safeEmail);
          return finalUser.id;
        }
        throw fallbackError;
      }
    }
    throw error; // P2002가 아닌 시스템 에러는 상위로 전파
  }
}
